Name: ' &2⛏ &6Wooden blocks &8| &f( &a176 &7blocks &f)'
Pages: 5
Permission_Required: true
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '&x&5&1&5&2&5&1&m                                           '
- ' &7This category contains different'
- '       &7types of wooden blocks!'
- ''
- '       &7⇦&a⇦&2⇦ &aClick to select! &2⇨&a⇨&7⇨'
- '&x&5&1&5&2&5&1&m                                           '
Icon:
  Material: OAK_LOG
Layout:
  Name: blockslog
